### ISSUE TITLE
cannot install the driver

### ISSUE THREAD

**Issue by Israel-Dayan** [etan8225/ForceLoudnessEQ#1]
cannot install the driver "Generic USB Audio" ant cannot find "High Definition Audio Device 10.0.19041.3636" version

**Comment by ethano8225** [comment]
Did you ensure to click on the "show incompatible drivers" (many of those drivers actually may or do work, but since it can't be guaranteed, they do not show that driver) and also:
Did you find any other, possibly newer versions of the High Definition Audio Device? I am on windows 10, which I know for a fact has a slightly older version of the HD audio driver.
What is your headset? Manufacturer and model.

**Comment by ethano8225** [comment]
Given that this has been open for a month with no response, I am closing it for now.
